---
- name: Backup files using rclone
  hosts: podman, proxmox
  gather_facts: no

  tasks:
    - name: Synchronize files
      command: "rclone copy {{ item.source }} {{ item.destination }} --checksum --log-file /var/log/rclone-backup.log --log-level INFO"
      loop: "{{ backup_files }}"
      loop_control:
        label: "{{ item.source }}"
      changed_when: false

    - name: Backup Proxmox LXC configs
      when: "'proxmox' in group_names"
      block:
        - name: Find LXC config files
          find:
            paths: /etc/pve/nodes/pve/lxc
            patterns: "*.conf"
          register: lxc_configs

        - name: Sync LXC configs to cloud
          command: "rclone copy {{ item.path }} opendrive:/lxc --checksum --log-file /var/log/rclone-backup.log --log-level INFO"
          loop: "{{ lxc_configs.files }}"
          loop_control:
            label: "{{ item.path }}"
          changed_when: false
