- name: Update caddy container
  hosts: podman
  tasks:
    - name: Get current image digest
      command: "podman image inspect --format '{% raw %}{{.Id}}{% endraw %}' docker.io/library/caddy:alpine"
      register: pre_pull_digest
      ignore_errors: yes
      changed_when: false

    - name: Pull latest image
      podman_image:
        name: docker.io/library/caddy:alpine
        force: true

    - name: Get new image digest
      command: "podman image inspect --format '{% raw %}{{.Id}}{% endraw %}' docker.io/library/caddy:alpine"
      register: post_pull_digest
      changed_when: false

    - name: Build custom image
      shell: podman build -t localhost/caddy:custom .
      args:
        chdir: /root/caddy
      when: pre_pull_digest.stdout is not defined or pre_pull_digest.stdout != post_pull_digest.stdout

    - name: Restart caddy if image updated
      shell: systemctl restart caddy.service
      when: pre_pull_digest.stdout is not defined or pre_pull_digest.stdout != post_pull_digest.stdout
