- name: Update container images
  hosts: podman
  vars:
    containers_to_ignore:
      - caddy
  tasks:
    - name: Get running container names
      shell: "podman ps --format '{% raw %}{{.Names}}{% endraw %}'"
      register: running_containers
      changed_when: false

    - name: Get container info
      podman_container_info:
        name: "{{ item }}"
      loop: "{{ running_containers.stdout_lines | reject('in', containers_to_ignore) | list }}"
      register: container_info

    - name: Get current image digests
      command: "podman image inspect --format '{% raw %}{{.Id}}{% endraw %}' {{ item.containers[0].ImageName }}"
      loop: "{{ container_info.results }}"
      loop_control:
        label: "{{ item.containers[0].ImageName }}"
      register: pre_pull_digests
      changed_when: false

    - name: Pull latest images
      podman_image:
        name: "{{ item.containers[0].ImageName }}"
        force: true
      loop: "{{ container_info.results }}"
      loop_control:
        label: "{{ item.containers[0].ImageName }}"

    - name: Get new image digests
      command: "podman image inspect --format '{% raw %}{{.Id}}{% endraw %}' {{ item.containers[0].ImageName }}"
      loop: "{{ container_info.results }}"
      loop_control:
        label: "{{ item.containers[0].ImageName }}"
      register: post_pull_digests
      changed_when: false

    - name: Restart containers if image updated
      shell: "systemctl restart {{ item.0.containers[0].Config.Labels.PODMAN_SYSTEMD_UNIT }}"
      loop: "{{ container_info.results | zip(pre_pull_digests.results, post_pull_digests.results) | list }}"
      when: item.1.stdout != item.2.stdout
      loop_control:
        label: "{{ item.0.containers[0].Name }}"
