---
- name: Update Secretariat client
  hosts: podman
  user: root
  vars:
    repo_owner: "Lurkars"
    repo_name: "gloomhavensecretariat"
    app_version_file: "version"
    app_install_dir: "/root/secretariat"
    base_url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/releases/latest"
    version_regex: "gloomhavensecretariat-v(.*)\\.zip"

  tasks:
    - name: Fetch latest release info
      ansible.builtin.uri:
        url: "{{ base_url }}"
        return_content: yes
      register: github_release_info

    - name: Set fact for download URL and version
      ansible.builtin.set_fact:
        download_url: "{{ (github_release_info.json.assets | selectattr('name', 'search', version_regex) | first).browser_download_url }}"
        latest_version: "{{ (github_release_info.json.assets | selectattr('name', 'search', version_regex) | first).name | regex_replace(version_regex, '\\1') }}"
      when: github_release_info.json.assets is defined
      
    - name: Latest version
      debug:
        msg: "Latest version: {{latest_version}}"
        
    - name: Check installed version
      ansible.builtin.slurp:
        src: "{{ app_install_dir }}/{{ app_version_file }}"
      register: installed_version_slurp
      ignore_errors: yes

    - name: Decode installed version content
      ansible.builtin.set_fact:
        installed_version: "{{ installed_version_slurp.content | b64decode | trim }}"
      when: installed_version_slurp.content is defined

    - name: Download and extract new version if needed
      when: installed_version is not defined or installed_version != latest_version
      block:
        - name: Update version
          debug:
            msg: "Updating from {{installed_version}} to {{latest_version}}"

        - name: Delete the install directory
          ansible.builtin.file:
            path: "{{ app_install_dir }}/gloomhavensecretariat"
            state: absent

        - name: Ensure application directory exists
          ansible.builtin.file:
            path: "{{ app_install_dir }}/gloomhavensecretariat"
            state: directory
            mode: '0755'

        - name: Download the latest release archive
          ansible.builtin.get_url:
            url: "{{ download_url }}"
            dest: "{{ app_install_dir }}/{{ repo_name }}_{{ latest_version }}.zip"
            mode: '0644'
            force: no

        - name: Extract the archive
          ansible.builtin.unarchive:
            src: "{{ app_install_dir }}/{{ repo_name }}_{{ latest_version }}.zip"
            dest: "{{ app_install_dir }}/gloomhavensecretariat"
            remote_src: yes

        - name: Create or update version file
          ansible.builtin.copy:
            content: "{{ latest_version }}"
            dest: "{{ app_install_dir }}/{{ app_version_file }}"

        - name: Clean up downloaded archive
          ansible.builtin.file:
            path: "{{ app_install_dir }}/{{ repo_name }}_{{ latest_version }}.zip"
            state: absent
